# Generated by Django 4.1.7 on 2023-03-07 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookingapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="amount_of_day",
        ),
        migrations.RemoveField(
            model_name="room",
            name="start_date",
        ),
    ]
