# Generated by Django 4.1.7 on 2023-03-07 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookingapp", "0003_remove_room_is_available"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="status",
        ),
    ]
